### PR TITLE
Node testing infrastructure

### LINKED ISSUE #4: Setup test infrastructure using NodeJS tools

### PR DESCRIPTION
**Pull request by jenschude**
Closes #4

### CODE REVIEW

**Comment by butenkor** [comment]
Just curious - What are the benefits of this setup comparing to existing one https://github.com/commercetools/commercetools-sunrise-scenarios/pull/1?

**Comment by jenschude** [comment]
The advantage is, that it's easier to write javascript and we are not sticking to one language which only few people in our team are firm with like #1 or #3. Also the PR #1 only provides the base infrastructure, but has not yet provided any step definitions regarding normal testing. So we would still have to build up all steps. The merged PR already has a lot of predefined steps for normal browser interaction. So you don't have to design a testing framework anymore.

Beside that the MC is also using Node and CucumberJs for their UI testing. So we are consolidating on one test environment

**Comment by butenkor** [comment]
Ok, Thanks 👍  Would be nice to have it in ES6.

**Comment by jenschude** [comment]
Yeah when i have time to rewrite it :D

**Pull request merged**
